name: hello-world-example
on:
  push:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -
        name: Say Hello
        run: echo "$GITHUB_WORKSPACE/index.php" >> $GITHUB_PATH
      -
        name: This is current path
        run: echo $GITHUB_PATH
